# Generated by Django 5.2.6 on 2025-09-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalelectro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
