# Generated by Django 5.2.6 on 2025-09-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalelectro_app', '0003_users_email_alter_users_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
