# Generated by Django 5.2.6 on 2025-09-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalelectro_app', '0003_customerorder_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='globalelectro_app.users'),
            preserve_default=False,
        ),
    ]
